### PR TITLE
Upgrade gradle to 8.2.1 and fix some warnings

### PR DESCRIPTION
**Pull request by nvervelle**
Hi !

Is the project still maintained ? Just want to know if I should send PR here or work on my own fork.

This is just an upgrade of gradle to the current version (allowing Java 17 for example) and fix of a few warnings issued by IntelliJ when committing the files.

I'm also interested in working on #41 , that is being able to use opa in docker for the plugin instead of locally installed opa. Tell me if you would be interested also

### CODE REVIEW

**Comment by anderseknert** [comment]
Hi @nvervelle! And thanks a lot for this contribution. It's vacation time for a lot of us, but I too am hoping this is maintained and will get merged into a new release 🙂

**Review by irodzik — APPROVED** [review]
LGTM

**Comment by radrys** [comment]
Hi @nvervelle ! Thanks for upgrading gradle version. The project is still maintained although not much work is currently going on. Feel free to work on #41 .

**Review by radrys — APPROVED** [review]

**Comment by nvervelle** [comment]
Great @radrys , ok I will take a look at #41 for an implementation of either using docker or automatically downloading opa

**Pull request merged**
